-- domuvai — initial schema
-- Generated by hand, reviewed against docs/RULES.md §4 (data model contract).
--
-- ADR-003  one database, one schema per module, RLS by entrance_id
-- ADR-005  the entrance is the only tenant key
-- ADR-006  money is integer minor units; ideal parts are exact decimals
-- ADR-001  every computed row carries basis_hash, law_version, engine_version
--
-- An invariant that the schema can enforce is never left to application code.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- uuid equality inside an EXCLUDE constraint

CREATE SCHEMA IF NOT EXISTS app;          -- session context helpers
CREATE SCHEMA IF NOT EXISTS registry;     -- ORG, BOOK
CREATE SCHEMA IF NOT EXISTS identity_org; -- GOV, PMC
CREATE SCHEMA IF NOT EXISTS assembly;     -- GA, VOTE
CREATE SCHEMA IF NOT EXISTS money;        -- FEE, FUND, DEBT
CREATE SCHEMA IF NOT EXISTS maintenance;  -- MNT
CREATE SCHEMA IF NOT EXISTS compliance;   -- REG
CREATE SCHEMA IF NOT EXISTS evidence;     -- DOC

-- ---------------------------------------------------------------- session
-- The tenant key is set per transaction. Nothing runs before it is known.
CREATE FUNCTION app.current_entrance() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('app.entrance_id', true), '')::uuid
$$;

-- ---------------------------------------------------------------- domains
-- Rule: PM-FEE-016 — money is integer minor units in EUR.
--
-- NOT bigint, and not numeric(18,0). Both of those accept 42.5 and silently
-- store 43, because Postgres rounds on an assignment cast — which is exactly
-- how a wrong bill gets a clean audit trail. Unconstrained numeric does not
-- round on assignment, so the scale check can actually reject the fraction.
-- Verified against all three in db/test/constraints.sh.
CREATE DOMAIN money_minor AS numeric
  CHECK (scale(VALUE) = 0);
CREATE DOMAIN currency_eur AS text CHECK (VALUE = 'EUR');

-- Rule: PM-ORG-002 — ideal parts as an exact decimal, per docs/RULES.md §4.
CREATE DOMAIN ideal_parts AS numeric(7,4)
  CHECK (VALUE >= 0 AND VALUE <= 100);

-- ================================================================ registry
CREATE TABLE registry.condominium (
  id            uuid PRIMARY KEY,
  address       text NOT NULL,
  cadastral_id  text,
  eis_code      text
);

-- Rule: PM-ORG-001 — ownership is modelled at the level of an entrance,
-- because each entrance may run its own assembly, manager and accounts.
CREATE TABLE registry.entrance (
  id               uuid PRIMARY KEY,
  condominium_id   uuid NOT NULL REFERENCES registry.condominium(id),
  label            text NOT NULL,
  management_form  text NOT NULL CHECK (management_form IN ('GA','ASSOCIATION','CLOSED_COMPLEX')),
  UNIQUE (condominium_id, label)
);

CREATE TABLE registry.unit (
  id                uuid PRIMARY KEY,
  entrance_id       uuid NOT NULL REFERENCES registry.entrance(id),
  designation       text NOT NULL,
  unit_type         text NOT NULL,
  area_m2           numeric(10,2) CHECK (area_m2 > 0),
  ideal_parts_pct   ideal_parts NOT NULL,
  -- Rule: PM-ORG-009 — business use through a separate street entrance
  separate_entrance boolean NOT NULL DEFAULT false,
  UNIQUE (entrance_id, designation)
);

-- Rule: PM-ORG-002 — the sum of ideal parts per entrance MUST equal 100%.
-- Across rows, so a CHECK cannot express it. A deferred constraint trigger
-- validates at COMMIT, which lets a multi-row import reach a valid state.
CREATE FUNCTION registry.assert_parts_sum_100() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE e uuid; total numeric;
BEGIN
  e := COALESCE(NEW.entrance_id, OLD.entrance_id);
  SELECT COALESCE(sum(ideal_parts_pct), 0) INTO total
    FROM registry.unit WHERE entrance_id = e;
  IF total <> 100.0000 THEN
    RAISE EXCEPTION 'ideal parts for entrance % sum to %, must be 100.0000 (PM-ORG-002)', e, total;
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER unit_parts_sum_100
  AFTER INSERT OR UPDATE OR DELETE ON registry.unit
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION registry.assert_parts_sum_100();

CREATE TABLE registry.party (
  id        uuid PRIMARY KEY,
  full_name text NOT NULL,
  id_type   text CHECK (id_type IN ('EGN','LNCH','BULSTAT','PASSPORT')),
  -- Rule: PM-BOOK-011 — never exposed in a list visible to other residents.
  id_value  text,
  contact   jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Rule: PM-ORG-005 — co-owned units split voting weight by title share,
-- and the system MUST prevent double counting.
-- Rule: PM-ORG-011 — ownership changes are effective-dated.
CREATE TABLE registry.title (
  id          uuid PRIMARY KEY,
  entrance_id uuid NOT NULL REFERENCES registry.entrance(id),
  unit_id     uuid NOT NULL REFERENCES registry.unit(id),
  party_id    uuid NOT NULL REFERENCES registry.party(id),
  title_role  text NOT NULL CHECK (title_role IN ('OWN','USR')),
  share       numeric(7,6) NOT NULL CHECK (share > 0 AND share <= 1),
  valid_from  date NOT NULL,
  valid_to    date,
  CHECK (valid_to IS NULL OR valid_to > valid_from),
  EXCLUDE USING gist (
    unit_id WITH =, party_id WITH =, title_role WITH =,
    daterange(valid_from, valid_to, '[)') WITH &&
  )
);

CREATE TABLE registry.household_member (
  id                uuid PRIMARY KEY,
  entrance_id       uuid NOT NULL REFERENCES registry.entrance(id),
  unit_id           uuid NOT NULL REFERENCES registry.unit(id),
  party_id          uuid REFERENCES registry.party(id),
  -- Rule: PM-FEE-005 — children under six are not counted
  is_child_under_6  boolean NOT NULL DEFAULT false,
  valid_from        date NOT NULL,
  valid_to          date,
  CHECK (valid_to IS NULL OR valid_to > valid_from)
);

-- Rule: PM-BOOK-005 / PM-FEE-009 — animals are a separate section of the book
-- and each counts as one occupant equivalent.
CREATE TABLE registry.animal (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  unit_id          uuid NOT NULL REFERENCES registry.unit(id),
  species          text NOT NULL,
  vet_passport_no  text,
  valid_from       date NOT NULL,
  valid_to         date
);

-- Rule: PM-FEE-006 / PM-FEE-007 — a filed non-use declaration. A unit whose occupants
-- are absent beyond the statutory window is exempt for the period; the exemption requires
-- a filed declaration, and a filing too late (PM-FEE-007) is not applied. Unlike residency,
-- an absence is a closed span: both bounds are known when it is declared. `filed_on` is set
-- by the system, not the caller — the filing date, not a claimed one, decides timeliness.
CREATE TABLE registry.absence_declaration (
  id            uuid PRIMARY KEY,
  entrance_id   uuid NOT NULL REFERENCES registry.entrance(id),
  unit_id       uuid NOT NULL REFERENCES registry.unit(id),
  absent_from   date NOT NULL,
  absent_to     date NOT NULL,               -- exclusive: the first day back
  filed_on      date NOT NULL,
  CHECK (absent_to > absent_from)
);

-- ============================================================ identity_org
-- Rule: PM-GOV-004 — a mandate MUST NOT exceed 2 years, and the incumbent
-- continues until a successor is elected.
CREATE TABLE identity_org.management_mandate (
  id                    uuid PRIMARY KEY,
  entrance_id           uuid NOT NULL REFERENCES registry.entrance(id),
  body                  text NOT NULL CHECK (body IN ('MB','BM','CTL','CSH','PMC')),
  party_id              uuid REFERENCES registry.party(id),
  elected_by_protocol   uuid,
  valid_from            date NOT NULL,
  valid_to              date NOT NULL,
  succeeded_at          date,
  CHECK (valid_to > valid_from),
  -- Rule: PM-GOV-004 — the two-year cap, as a constraint rather than a reminder
  CHECK (valid_to <= valid_from + INTERVAL '2 years')
);

-- ================================================================ assembly
CREATE TABLE assembly.assembly (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  convened_by      uuid REFERENCES registry.party(id),
  notice_posted_at timestamptz,
  scheduled_at     timestamptz NOT NULL,
  mode             text NOT NULL CHECK (mode IN ('IN_PERSON','VIDEO','HYBRID')),
  status           text NOT NULL
);

-- Rule: PM-GA-012/013/014 — the quorum ladder: 51%, then 26% one hour later,
-- then any share the following day. Each is its own session of one assembly.
CREATE TABLE assembly.session (
  id            uuid PRIMARY KEY,
  entrance_id   uuid NOT NULL REFERENCES registry.entrance(id),
  assembly_id   uuid NOT NULL REFERENCES assembly.assembly(id),
  session_no    smallint NOT NULL CHECK (session_no BETWEEN 1 AND 3),
  opened_at     timestamptz,
  represented   ideal_parts,
  quorum_met    boolean,
  UNIQUE (assembly_id, session_no)
);

CREATE TABLE assembly.agenda_item (
  id                uuid PRIMARY KEY,
  entrance_id       uuid NOT NULL REFERENCES registry.entrance(id),
  assembly_id       uuid NOT NULL REFERENCES assembly.assembly(id),
  ordinal           smallint NOT NULL,
  text              text NOT NULL,
  -- Rule: PM-VOTE-001 — an item is bound to its majority rule before the
  -- meeting opens. NOT NULL is that rule, enforced.
  majority_rule_id  text NOT NULL,
  UNIQUE (assembly_id, ordinal)
);

-- Rule: PM-VOTE-011/012 — the denominator is stored explicitly, never implied.
CREATE TABLE assembly.decision (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  agenda_item_id   uuid NOT NULL REFERENCES assembly.agenda_item(id),
  session_no       smallint NOT NULL,
  majority_rule_id text NOT NULL,
  denominator      text NOT NULL CHECK (denominator IN ('TOTAL','REPRESENTED')),
  threshold_pct    ideal_parts NOT NULL,
  tally_for        ideal_parts NOT NULL,
  tally_against    ideal_parts NOT NULL,
  status           text NOT NULL CHECK (status IN ('PROVISIONAL','FINAL','ANNULLED')),
  execution_due    date,
  law_version      text NOT NULL,
  engine_version   text NOT NULL,
  decided_at       timestamptz NOT NULL DEFAULT now()
);

-- Rule: PM-VOTE-014 — a vote cannot be edited once the item is closed;
-- corrections are annotated reversals. Enforced by a rule, not a convention.
CREATE TABLE assembly.vote (
  id              uuid PRIMARY KEY,
  entrance_id     uuid NOT NULL REFERENCES registry.entrance(id),
  agenda_item_id  uuid NOT NULL REFERENCES assembly.agenda_item(id),
  party_id        uuid NOT NULL REFERENCES registry.party(id),
  unit_id         uuid NOT NULL REFERENCES registry.unit(id),
  weight          ideal_parts NOT NULL,
  choice          text NOT NULL CHECK (choice IN ('FOR','AGAINST','ABSTAIN')),
  channel         text NOT NULL CHECK (channel IN ('IN_PERSON','PROXY','VIDEO','ABSENTEE')),
  cast_at         timestamptz NOT NULL DEFAULT now(),
  reverses        uuid REFERENCES assembly.vote(id),
  -- Rule: PM-ORG-005 — one vote per party per unit per item; no double counting
  UNIQUE (agenda_item_id, party_id, unit_id)
);
CREATE RULE vote_no_update AS ON UPDATE TO assembly.vote DO INSTEAD NOTHING;
CREATE RULE vote_no_delete AS ON DELETE TO assembly.vote DO INSTEAD NOTHING;

CREATE TABLE assembly.protocol (
  id              uuid PRIMARY KEY,
  entrance_id     uuid NOT NULL REFERENCES registry.entrance(id),
  assembly_id     uuid NOT NULL REFERENCES assembly.assembly(id),
  drafted_at      timestamptz,
  announced_at    timestamptz,
  appeal_deadline date,
  file_hash       text,
  -- Rule: PM-GA-020 — the appeal clock starts from the announcement, so one
  -- cannot exist without the other.
  CHECK ((announced_at IS NULL) = (appeal_deadline IS NULL))
);

-- =================================================================== money
-- Rule: PM-FEE-014 — a charge run stores the basis that produced it.
-- Rule: ADR-001 amendment — and the engine version, not only the law version.
CREATE TABLE money.charge_run (
  id              uuid PRIMARY KEY,
  entrance_id     uuid NOT NULL REFERENCES registry.entrance(id),
  period          text NOT NULL CHECK (period ~ '^\d{4}-\d{2}$'),
  legal_date      date NOT NULL,
  basis           jsonb NOT NULL,
  basis_hash      text NOT NULL,
  law_version     text NOT NULL,
  engine_version  text NOT NULL,
  status          text NOT NULL CHECK (status IN ('PENDING','RUNNING','COMPLETE','FAILED')),
  cursor_unit_id  uuid,
  UNIQUE (entrance_id, period)
);

CREATE TABLE money.charge_line (
  id              uuid PRIMARY KEY,
  entrance_id     uuid NOT NULL REFERENCES registry.entrance(id),
  charge_run_id   uuid NOT NULL REFERENCES money.charge_run(id),
  unit_id         uuid NOT NULL REFERENCES registry.unit(id),
  component       text NOT NULL CHECK (component IN ('MANAGEMENT','MAINTENANCE','REPAIR_FUND')),
  allocation_key  text NOT NULL CHECK (allocation_key IN ('PER_PERSON','BY_IDEAL_PARTS','PER_UNIT')),
  quantity        numeric(12,6) NOT NULL,
  amount_minor    money_minor NOT NULL,
  currency        currency_eur NOT NULL DEFAULT 'EUR',
  derivation      text NOT NULL,     -- Rule: PM-FEE-018
  -- idempotent per unit per run, so a resumed run writes nothing twice
  UNIQUE (charge_run_id, unit_id, component)
);
-- Rule: PM-FEE-015 — an issued bill is never rewritten; corrections are notes.
CREATE RULE charge_line_no_update AS ON UPDATE TO money.charge_line DO INSTEAD NOTHING;

-- Rule: PM-FUND-004 — the fund account is in the chair's or the association's
-- name. Rule: PM-FUND-005 / PM-PMC-008 — never commingled, never transferable.
CREATE TABLE money.fund_account (
  id           uuid PRIMARY KEY,
  entrance_id  uuid NOT NULL REFERENCES registry.entrance(id),
  iban         text NOT NULL,
  purpose      text NOT NULL CHECK (purpose IN ('REPAIR_RENEWAL','OPERATING')),
  -- Rule: PM-FUND-004 — the holder is the chair of the management board (manager) or the
  -- association, never the platform (ADR-007). `holder_name`/`holder_kind` state the holder;
  -- `holder_party` is the precise link to the book's party record when there is one (nullable,
  -- because the association or an as-yet-unregistered chair may not be a modelled party).
  holder_name  text NOT NULL,
  holder_kind  text NOT NULL CHECK (holder_kind IN ('MANAGER','ASSOCIATION')),
  holder_party uuid REFERENCES registry.party(id),
  -- one account per entrance per purpose, and one IBAN across all entrances: the fund cannot
  -- equal the operating account (PM-FUND-004) and monies cannot be commingled (PM-FUND-005).
  UNIQUE (entrance_id, purpose),
  UNIQUE (iban)
);
-- The account holds no balance here: the platform never holds fund monies (ADR-007). This row
-- is only the external чл. 50 account a payment initiation would target; a balance is derived
-- from postings, never stored.

-- Double-entry. Rule: ADR-006 — a balance is derived, never stored.
CREATE TABLE money.posting (
  id            uuid PRIMARY KEY,
  entrance_id   uuid NOT NULL REFERENCES registry.entrance(id),
  journal_id    uuid NOT NULL,
  account       text NOT NULL,
  unit_id       uuid REFERENCES registry.unit(id),
  amount_minor  money_minor NOT NULL,
  currency      currency_eur NOT NULL DEFAULT 'EUR',
  value_date    date NOT NULL,
  posted_at     timestamptz NOT NULL DEFAULT now()
);
CREATE RULE posting_no_update AS ON UPDATE TO money.posting DO INSTEAD NOTHING;
CREATE RULE posting_no_delete AS ON DELETE TO money.posting DO INSTEAD NOTHING;

-- A journal must balance to zero. Deferred, so both legs can be written.
CREATE FUNCTION money.assert_journal_balances() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE s bigint;
BEGIN
  SELECT COALESCE(sum(amount_minor), 0) INTO s
    FROM money.posting WHERE journal_id = NEW.journal_id;
  IF s <> 0 THEN
    RAISE EXCEPTION 'journal % does not balance: % minor units (ADR-006)', NEW.journal_id, s;
  END IF;
  RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER posting_balances
  AFTER INSERT ON money.posting
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION money.assert_journal_balances();

CREATE TABLE money.arrear (
  id            uuid PRIMARY KEY,
  entrance_id   uuid NOT NULL REFERENCES registry.entrance(id),
  unit_id       uuid NOT NULL REFERENCES registry.unit(id),
  -- Rule: PM-DEBT-012 — an arrear attaches to the party liable when it accrued
  party_id      uuid NOT NULL REFERENCES registry.party(id),
  amount_minor  money_minor NOT NULL CHECK (amount_minor > 0),
  currency      currency_eur NOT NULL DEFAULT 'EUR',
  due_date      date NOT NULL,
  paid_at       timestamptz,
  dunning_stage text NOT NULL DEFAULT 'NONE'
    CHECK (dunning_stage IN ('NONE','REMINDER','FORMAL_NOTICE','DECISION','ORDER_410'))
);

-- ============================================================= maintenance
CREATE TABLE maintenance.work_order (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  category         text NOT NULL,
  -- Rule: PM-MNT-001 — the class decides the majority and the funding source
  work_class       text NOT NULL CHECK (work_class IN ('NECESSARY','URGENT','USEFUL','LUXURY')),
  budget_source    text NOT NULL CHECK (budget_source IN ('REPAIR_FUND','OPERATING','OWNER')),
  decision_id      uuid REFERENCES assembly.decision(id),
  estimated_minor  money_minor,
  actual_minor     money_minor,
  raised_at        timestamptz NOT NULL DEFAULT now(),
  closed_on        date,
  warranty_until   date
);

-- ============================================================== compliance
CREATE TABLE compliance.task (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  obligation_code  text NOT NULL,
  rule_id          text NOT NULL CHECK (rule_id ~ '^PM-[A-Z]+-\d{3}$'),
  due_date         date NOT NULL,
  owner_party_id   uuid REFERENCES registry.party(id),
  evidence_doc_id  uuid,
  completed_at     timestamptz
);

CREATE TABLE compliance.registry_filing (
  id           uuid PRIMARY KEY,
  entrance_id  uuid NOT NULL REFERENCES registry.entrance(id),
  registry     text NOT NULL CHECK (registry IN ('MUNICIPAL','EIS','BULSTAT')),
  filed_at     timestamptz,
  ack_ref      text,
  -- Rule: PM-REG-008 — a filing is not done until the authority acknowledges
  acknowledged_at timestamptz,
  CHECK ((ack_ref IS NULL) = (acknowledged_at IS NULL))
);

-- ================================================================ evidence
-- Rule: PM-DOC-001 — immutable, content-addressed, with author and timestamp.
CREATE TABLE evidence.document (
  id               uuid PRIMARY KEY,
  entrance_id      uuid NOT NULL REFERENCES registry.entrance(id),
  entity_ref       text NOT NULL,
  kind             text NOT NULL,
  content_hash     text NOT NULL,
  stored_at        timestamptz NOT NULL DEFAULT now(),
  author_party_id  uuid REFERENCES registry.party(id),
  retention_until  date,
  signed_by        jsonb,
  -- Rule: PM-DOC-007 — where the law wants paper, record where the paper is
  paper_location   text
);
CREATE RULE document_no_update AS ON UPDATE TO evidence.document DO INSTEAD NOTHING;
CREATE RULE document_no_delete AS ON DELETE TO evidence.document DO INSTEAD NOTHING;

COMMIT;
