#!/usr/bin/env python3
"""A11 — the test plan. Turns 233 rules into a ranked, sliceable worklist.

Not a document anyone maintains by hand: it is generated from rules.json and the
current traceability, so it shrinks as the tests land and can never claim
coverage the source tree does not have.

Ordering is by the gate a rule serves, because a gate is the only thing that can
tell us the rules are wrong. Within a gate: MUST before SHOULD, and rules whose
number is unconfirmed are flagged — their mechanism is testable today even while
the number waits on counsel.
"""
import json, re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = json.loads((ROOT/'docs/rules.json').read_text())
OUT = ROOT/'docs/TESTPLAN.md'

# Which gate each rule domain serves. A gate is a stop that proves something
# about reality; everything else is scheduling. See docs/SEQUENCE.md §4.
GATE = {
    'ORG': 1, 'BOOK': 1, 'FEE': 1, 'FUND': 1, 'SYS': 1,
    'GOV': 2, 'GA': 2, 'VOTE': 2, 'DOC': 2, 'SEC': 2,
    'DEBT': 3,
    'MNT': 4, 'REG': 4, 'PMC': 4, 'AI': 4, 'LAW': 4,
}
GATE_NAME = {
    1: 'Gate 1 — the fee engine reproduces the firm\'s spreadsheet to the cent',
    2: 'Gate 2 — one lawful general assembly, end to end',
    3: 'Gate 3 — collection beats their portfolio average',
    4: 'Gate 4 — the risk board is credible',
}
# Which module owns the domain (ADR-003, fourteen modules)
MODULE = {
    'ORG': 'registry', 'BOOK': 'registry', 'GOV': 'identity-org', 'PMC': 'identity-org',
    'GA': 'assembly', 'VOTE': 'assembly',
    'FEE': 'money', 'FUND': 'money', 'DEBT': 'money',
    'MNT': 'maintenance', 'REG': 'compliance', 'DOC': 'evidence',
    'SEC': 'policy', 'SYS': 'kernel', 'AI': 'agent', 'LAW': 'law',
}
MODALITY_RANK = {'MUST': 0, 'MUST NOT': 0, 'SHOULD': 1, 'MAY': 2}
SLICE_SIZE = 10        # rules per slice — one module, ~400 lines of diff

RULE_RE = re.compile(r'PM-[A-Z]+-\d{3}')
TEST_RE = re.compile(r"fun\s+`(PM-[A-Z]+-\d{3})")

def covered() -> set[str]:
    out = set()
    for p in ROOT.rglob('*.kt'):
        if 'build' in p.parts or 'node_modules' in p.parts: continue
        out |= set(TEST_RE.findall(p.read_text()))
    return out

def main() -> int:
    done = covered()
    rules = RULES['rules']
    todo = [r for r in rules if r['id'] not in done]

    def key(r):
        # Module before modality: a slice is one module, so keeping a module's
        # rules adjacent is what makes the slices coherent rather than one-deep.
        return (GATE.get(r['domain'], 9), MODULE[r['domain']],
                MODALITY_RANK.get(r['modality'], 3),
                0 if not r.get('verified') else 1, r['id'])
    todo.sort(key=key)

    # build slices: same module, same gate, at most SLICE_SIZE
    slices, cur = [], []
    for r in todo:
        if cur and (MODULE[cur[0]['domain']] != MODULE[r['domain']]
                    or GATE[cur[0]['domain']] != GATE[r['domain']]
                    or len(cur) >= SLICE_SIZE):  # one module per slice
            slices.append(cur); cur = []
        cur.append(r)
    if cur: slices.append(cur)

    # Merge a short tail back into the slice before it when they share a module
    # and a gate. A one-rule slice is not a slice; it is an errand.
    merged = []
    for sl in slices:
        if (merged and len(sl) < 4
                and MODULE[merged[-1][0]['domain']] == MODULE[sl[0]['domain']]
                and GATE[merged[-1][0]['domain']] == GATE[sl[0]['domain']]):
            merged[-1].extend(sl)
        else:
            merged.append(sl)
    slices = merged

    pct = round(100 * len(done & {r['id'] for r in rules}) / len(rules))
    L = ["# Test plan", "",
         "**Generated by `tools/testplan.py`. Do not edit.** It shrinks as tests land.", "",
         f"| | Count |", "|---|---|",
         f"| Rules in catalogue | **{len(rules)}** |",
         f"| Every rule carries an acceptance criterion | yes — all {len(rules)} are testable as written |",
         f"| Proved by a test named after the rule | **{len(rules) - len(todo)}** ({pct}%) |",
         f"| Remaining | **{len(todo)}** |",
         f"| Proposed slices at ~{SLICE_SIZE} rules each | **{len(slices)}** |", "",
         "Ordered by the gate each rule serves. A gate is the only thing that can tell us "
         "the rules are wrong; everything else is scheduling. Within a gate: MUST before "
         "SHOULD, and a rule whose number is unconfirmed comes first — its *mechanism* is "
         "testable today, with the number read from configuration while counsel answers.", ""]

    for g in (1, 2, 3, 4):
        gs = [s for s in slices if GATE[s[0]['domain']] == g]
        if not gs: continue
        n = sum(len(s) for s in gs)
        L += [f"## {GATE_NAME[g]}", "", f"{n} rule(s) remaining across {len(gs)} slice(s).", ""]
        for i, s in enumerate(gs, 1):
            mod = MODULE[s[0]['domain']]
            dom = ' · '.join(sorted({r['domain'] for r in s}))
            unv = sum(1 for r in s if not r.get('verified'))
            L += [f"### S-G{g}-{i:02d} · `{mod}` · {dom} · {len(s)} rule(s)"
                  + (f" · ⚠ {unv} unconfirmed" if unv else ""), "",
                  "| Rule | | Test must prove |", "|---|---|---|"]
            for r in s:
                acc = (r.get('acceptance') or '—').replace('|', '\\|')
                L.append(f"| `{r['id']}` | {r['modality']}{' ⚠' if not r.get('verified') else ''} | {acc} |")
            L.append("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"OK  {len(todo)} rules remaining  ·  {len(slices)} slices  ·  {pct}% covered")
    return 0

if __name__ == '__main__':
    sys.exit(main())
