#!/usr/bin/env python3
"""A7 — rule traceability. Generates docs/TRACEABILITY.md from rules.json and the
source tree. Fails when code cites a rule ID the catalogue does not contain, or
when coverage falls below the floor recorded in the report it replaces."""
import json, re, sys, pathlib, argparse

ROOT = pathlib.Path(__file__).resolve().parent.parent
RULES = json.loads((ROOT/'docs/rules.json').read_text())
OUT = ROOT/'docs/TRACEABILITY.md'
# sorted(): rglob order is filesystem-dependent, and an unsorted scan makes the
# generated report differ between machines — which fails the docs-in-sync gate
# for no real reason.
SRC = sorted(p for d in ('packages','apps') for p in (ROOT/d).rglob('*.ts')
             if 'node_modules' not in p.parts)

RULE_RE = re.compile(r'PM-[A-Z]+-\d{3}')
TEST_RE = re.compile(r"""(?:test|it)\(\s*['"`](PM-[A-Z]+-\d{3}[^'"`]*)""")

def scan():
    impl, test, cited = {}, {}, {}
    for p in SRC:
        rel = p.relative_to(ROOT)
        for i, line in enumerate(p.read_text().splitlines(), 1):
            for m in TEST_RE.finditer(line):
                for r in RULE_RE.findall(m.group(1)):
                    test.setdefault(r, []).append(f"{rel}:{i}")
            # Attribution is strict: only a `Rule:` tag counts as an implementation claim.
            if re.search(r'(?://|\*|/\*\*).*Rule:', line):
                for r in RULE_RE.findall(line):
                    impl.setdefault(r, []).append(f"{rel}:{i}")
            # Orphan detection is broad: ANY rule ID anywhere in source must exist
            # in the catalogue, however it was written.
            for r in RULE_RE.findall(line):
                cited.setdefault(r, []).append(f"{rel}:{i}")
        # a rule named in a test title counts as implemented wherever it is asserted
    return impl, test, cited

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--min-coverage', type=int, default=0,
                    help='fail if the percentage of rules with a test falls below this')
    args = ap.parse_args()

    ids = [r['id'] for r in RULES['rules']]
    known = set(ids)
    impl, test, cited = scan()

    orphans = sorted((set(cited) | set(test)) - known)
    if orphans:
        print("INTEGRITY FAILURE — rule IDs cited in code that are not in rules.json:")
        for o in orphans:
            print(f"  {o}  at {', '.join((cited.get(o) or []) + (test.get(o) or []))[:120]}")
        return 1

    by_dom = {}
    for r in RULES['rules']:
        by_dom.setdefault(r['domain'], []).append(r)

    covered = sorted(set(test) & known)
    touched = sorted((set(test) | set(impl)) & known)
    pct = round(100 * len(covered) / len(ids))

    L = [f"# Traceability",
         "",
         f"**Generated by `tools/traceability.py`. Do not edit.** "
         f"Catalogue v{RULES['meta']['version']}, {len(ids)} rules.",
         "",
         f"| | Count | Share |",
         f"|---|---|---|",
         f"| Rules in catalogue | **{len(ids)}** | 100% |",
         f"| Referenced in code (`// Rule:`) | {len(set(impl) & known)} | {round(100*len(set(impl)&known)/len(ids))}% |",
         f"| **Proved by a test named after the rule** | **{len(covered)}** | **{pct}%** |",
         f"| No implementation and no test | {len(ids) - len(touched)} | {round(100*(len(ids)-len(touched))/len(ids))}% |",
         "",
         "A rule is *covered* only when a test is named after its ID. A `// Rule:` "
         "comment with no test is a claim, not evidence.",
         ""]

    for dom in RULES['domains']:
        rs = by_dom.get(dom['code'], [])
        c = sum(1 for r in rs if r['id'] in test)
        L += [f"## {dom['code']} — {dom['title']}  ·  {c}/{len(rs)} covered", "",
              "| Rule | Test | Implementation | Unverified |", "|---|---|---|---|"]
        for r in rs:
            t = test.get(r['id']); im = impl.get(r['id'])
            L.append(f"| `{r['id']}` | {'`'+t[0]+'`' if t else '—'} | "
                     f"{'`'+im[0]+'`' if im else '—'} | {'⚠' if not r.get('verified') else ''} |")
        L.append("")

    OUT.write_text("\n".join(L) + "\n")
    print(f"OK  {len(covered)}/{len(ids)} rules covered by a named test ({pct}%)  ·  "
          f"{len(set(impl)&known)} referenced  ·  0 orphan IDs")
    if pct < args.min_coverage:
        print(f"FAIL  coverage {pct}% is below the floor of {args.min_coverage}%")
        return 1
    return 0

if __name__ == '__main__':
    sys.exit(main())
